### ISSUE TITLE
Error: Unable to access jarfile

### ISSUE THREAD

**Issue by nodecentral** [bengtmartensson/IrpTransmogrifier#193]
Hi

I’m trying to run IrpTransmogrifier on my pi, but I can’t seem to get it to work. Please could you help direct me on what’s wrong..

`pi@raspberrypi:~/IrpTransmogrifier-master $ ls -la
total 144
drwxr-xr-x  6 pi pi  4096 Oct  4 11:30 .
drwxr-xr-x 29 pi pi  4096 Nov  7 09:40 ..
drwxr-xr-x  8 pi pi  4096 Oct  4 11:30 common
drwxr-xr-x  6 pi pi  4096 Oct  4 11:30 contributed
-rw-r--r--  1 pi pi  1208 Oct  4 11:30 CONTRIBUTING.md
drwxr-xr-x  3 pi pi  4096 Oct  4 11:30 .github
-rw-r--r--  1 pi pi   349 Oct  4 11:30 .gitignore
-rwxr-xr-x  1 pi pi   418 Oct  4 11:30 irptransmogrifier
-rw-r--r--  1 pi pi 35142 Oct  4 11:30 LICENSE
-rw-r--r--  1 pi pi  3529 Oct  4 11:30 Makefile
-rw-r--r--  1 pi pi 23739 Oct  4 11:30 pom.xml
-rw-r--r--  1 pi pi 33269 Oct  4 11:30 README.md
-rw-r--r--  1 pi pi  1215 Oct  4 11:30 ROADMAP.md
drwxr-xr-x  5 pi pi  4096 Oct  4 11:30 src
-rw-r--r--  1 pi pi   478 Oct  4 11:30 .travis.yml

pi@raspberrypi:~/IrpTransmogrifier-master $ java -version
openjdk version "1.8.0_40-internal"
OpenJDK Runtime Environment (build 1.8.0_40-internal-b04)
OpenJDK Zero VM (build 25.40-b08, interpreted mode)

pi@raspberrypi:~/IrpTransmogrifier-master $ ./irptransmogrifier
./irptransmogrifier: 1: ./irptransmogrifier: xpath: not found
Error: Unable to access jarfile /home/pi/IrpTransmogrifier-master/target/IrpTransmogrifier--jar-with-dependencies.jar

pi@raspberrypi:~/IrpTransmogrifier-master $ `

**Comment by bengtmartensson** [comment]
You did not follow the [instructions](http://www.harctoolbox.org/IrpTransmogrifier.html#Installation) (alternatively README.md).

**Comment by nodecentral** [comment]
Please could you help me out, what am I not doing (Linux is not something I know very well) ? 

It says 

“ The program is basically just an executable jar-file. There is no "installer". Instead, unpack the binary distribution in a preferably empty directory. Start the program by invoking the wrapper ... irptransmogrifier.sh on Unix-like systems like Linux”

So I do this , which I believe is how you execute the irptransmogrifier.sh

``pi@raspberrypi:~/IrpTransmogrifier-master $ ./irptransmogrifier
`
Which then returns this error ? 

```
./irptransmogrifier: 1: ./irptransmogrifier: xpath: not found
Error: Unable to access jarfile /home/pi/IrpTransmogrifier-master/target/IrpTransmogrifier--jar-with-dependencies.jar
```

`

**Comment by bengtmartensson** [comment]
The wrapper to be used is `irptransmogrifier.sh` which is not the same as `irptransmogrifier`. It is found at the top level in the binary distribution and in src/main/config. The instructions are correct.

**Comment by nodecentral** [comment]
Great thanks - I still end up with an error going that way too.

`pi@raspberrypi:~/IrpTransmogrifier-master/src/main/config $ ls
irptransmogrifier.bat  irptransmogrifier.sh
pi@raspberrypi:~/IrpTransmogrifier-master/src/main/config $ sudo ./irptransmogrifier.sh
./irptransmogrifier.sh: 9: ./irptransmogrifier.sh: Bad substitution `

**Comment by bengtmartensson** [comment]
Ok, the statement

> It is found at the top level in the binary distribution and in src/main/config.

was slightly misleading since these are not equal: the first one is created from the first during build; the second one cannot be executed directly. I apologize for this mistake.

**Comment by nodecentral** [comment]
No problem 

please could you help me with what I need to do instead ? 

(Huge thanks in advance)

**Comment by nodecentral** [comment]
There only seems to be one file..

`pi@raspberrypi:~/IrpTransmogrifier-master $ find . -name 'irptransmogrifier.sh'
./src/main/config/irptransmogrifier.sh `

**Comment by nodecentral** [comment]
I’ve just tried to download one of your ‘snapshots’ to see if that helps, but sadly not.

`pi@raspberrypi:~/Downloads $ unzip IrpTransmogrifier-1.2.10-SNAPSHOT-bin.zip
Archive:  IrpTransmogrifier-1.2.10-SNAPSHOT-bin.zip
  inflating: README.md               
  inflating: LICENSE                 
  inflating: IrpProtocols.html       
  inflating: IrpTransmogrifier.xml   
  inflating: IrpTransmogrifier-1.2.10-SNAPSHOT.jar  
  inflating: irp-protocols.xsd       
  inflating: IrpTransmogrifier-1.2.10-SNAPSHOT-jar-with-dependencies.jar  
  inflating: IrpProtocols.xml        
  inflating: IrpProtocols2html.xsl   
  inflating: irptransmogrifier.bat   
  inflating: IrpTransmogrifier.html  
  inflating: irptransmogrifier.sh    
pi@raspberrypi:~/Downloads $ ./irptransmogrifier.sh
Command missing.`

**Comment by bengtmartensson** [comment]
That is the correct output since, surprise surprise, a command is missing.
