### ISSUE TITLE
IRP variant implicitly repeats (+ or *)?

### ISSUE THREAD

**Issue by seanyoung** [bengtmartensson/IrpTransmogrifier#200]
If a stream has no repeat operator, then no repeats are generated.
```
$ ./irptransmogrifier.sh --irp '{100}<1,-1|1,-3>(1,-10,10:10,1,-100m) ' render -r --number-repeats 10
[+100,-1000,+100,-100,+100,-300,+100,-100,+100,-300,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100000]
```
However, if we add a variant, now it starts repeating:
```
$ ./irptransmogrifier.sh --irp '{100}<1,-1|1,-3>([1][2],-10,10:10,1,-100m)' render -r --number-repeats 10
[+100,-1000,+100,-100,+100,-300,+100,-100,+100,-300,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100000,+200,-1000,+100,-100,+100,-300,+100,-100,+100,-300,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100000,+200,-1000,+100,-100,+100,-300,+100,-100,+100,-300,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100000,+200,-1000,+100,-100,+100,-300,+100,-100,+100,-300,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100000,+200,-1000,+100,-100,+100,-300,+100,-100,+100,-300,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100000,+200,-1000,+100,-100,+100,-300,+100,-100,+100,-300,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100000,+200,-1000,+100,-100,+100,-300,+100,-100,+100,-300,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100000,+200,-1000,+100,-100,+100,-300,+100,-100,+100,-300,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100000,+200,-1000,+100,-100,+100,-300,+100,-100,+100,-300,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100000,+200,-1000,+100,-100,+100,-300,+100,-100,+100,-300,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100000,+200,-1000,+100,-100,+100,-300,+100,-100,+100,-300,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100,+100,-100000]
```
Now the repeating operator is not explicit, so it is not immediate clear which one is used. I think the `+` is used so, so with the explicit + operator it would look like `{100}<1,-1|1,-3>([1][2],-10,10:10,1,-100m)+`. Or is it `*`? Not clear.

I think IrpTransmogrifier should not accept variant without the repeat operator, or not implicitly start repeating. Also  the `RCA(Old)` protocol in IrpProtocols.xml should be updated with an explicit repeat operator.

**Comment by bengtmartensson** [comment]
Sign,... I see that I had not read the description carefully enough; it clearly states that [a variation is a permitted type of irstream item that operates in conjunction with a repeat marker for the irstream that contains it.](http://www.hifi-remote.com/wiki/index.php/IRP_Notation#Semantics_11)

Thanx for bringing the problem to my attention. Will look into it.

**Comment by seanyoung** [comment]
Thanks!

**Comment by seanyoung** [comment]
If there is a 3rd variant, then the iteration does change: an extra iteration is done for the trailing variant. 

The semantics are hard to pin down.

**Comment by bengtmartensson** [comment]
I recently pushed a proposed fix to branch variations-fix. This is available as the continous build, for a short time. Please let me know what you think.

1. Protocol with variations but without (infinite) repeat are prohibited (throws UnsupportedRepeatException).
2. Similar for protocols with variations with non-empty intro part but repeat "*".
3. Protocols correspondingly fixed.
4. Bug in generating of ending sequence fixed.

**Comment by seanyoung** [comment]
I think this makes a lot of sense, thank you. The code and tests look good.

**Comment by bengtmartensson** [comment]
[Thread in the JP1-forum](http://www.hifi-remote.com/forums/viewtopic.php?t=102771)
