### ISSUE TITLE
IrSignal: Do not nuke intro- and repeat-sequences because they are identical to the repeat sequence.

### ISSUE THREAD

**Issue by bengtmartensson** [bengtmartensson/IrpTransmogrifier#224]
In constructors of IrSignal, it is checked of intro- and repeat- are identical (numerically) to the repeat, and if so, replaced by empty sequences (IrSignal.java, IrSignal.setup(...)). I cannot quite recall the rationale for this; if so, it should be done on protocols, not on individual IrSignals. @seanyoung has shown that in some cases (#222, #223) it may have unexpected consequences.

I will just remove this questionable feature, and see if something nasty appears.

**Comment by seanyoung** [comment]
Looks perfect, thank you very much @bengtmartensson for fixing this :pray:
