### ISSUE TITLE
Render fails with Argument of extent smaller than actual duration

### ISSUE THREAD

**Issue by seanyoung** [bengtmartensson/IrpTransmogrifier#226]
This render does not work for some reason.

```bash
$  ./irptransmogrifier.sh --irp '{38.4k,msb,564}<1,-1|1,-3>(16,-8,data:length,1,^108m) [data:0..UINT32_MAX,length:1..64]' render -r -n data=2663317484,length=60
data=2663317484,length=60
Argument of extent smaller than actual duration.
```

**Comment by seanyoung** [comment]
I am wondering if `NEC-Shirriff` parameter should be updated to `length:1..32`.

**Comment by bengtmartensson** [comment]
> Argument of extent smaller than actual duration.

Actually not a very stupid error message. Argument of extent = 108m, actual duration is more than that, so it is hard to pad to 108millis... (crystal balls not allowed ;-). 

> I am wondering if NEC-Shirriff parameter should be updated to length:1..32.

Probably better possibly to replace the extent by a "dumb" duration. Said protocol is by and for hobbyists, not for serious usage.

**Comment by seanyoung** [comment]
> > Argument of extent smaller than actual duration.
> 
> Actually not a very stupid error message. Argument of extent = 108m, actual duration is more than that, so it is hard to pad to 108millis... (crystal balls not allowed ;-).

Ah of course, that is very clear, my bad :grin: 
 
> > I am wondering if NEC-Shirriff parameter should be updated to length:1..32.
> 
> Probably better possibly to replace the extent by a "dumb" duration. Said protocol is by and for hobbyists, not for serious usage.

However with `data:0..UINT32_MAX` any length > 32 is just going to be adding zero bits. Is that really what's intended?

Either way this can happen when random parameters are picked, so it would be nice to one solution or another

**Comment by bengtmartensson** [comment]
Probably the most consistent with the "hobbyist nature" would be to remove the parameter specs altogether...
