### ISSUE TITLE
Bug in JCommander: repeated boolean option flips that option

### ISSUE THREAD

**Issue by bengtmartensson** [bengtmartensson/IrpTransmogrifier#228]
```
$ irptransmogrifier render denon-k --name D=4,S=1,F=368 --pronto 
0000 0070 0000 0032 0080 0040 0010 0010 0010 0010 0010 0030 0010 0010 0010 0030 0010 0010 0010 0030 0010 0010 0010 0010 0010 0030 0010 0010 0010 0010 0010 0030 0010 0030 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0030 0010 0010 0010 0030 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0010 0030 0010 0030 0010 0030 0010 0010 0010 0030 0010 0010 0010 0010 0010 0010 0010 0010 0010 0030 0010 0030 0010 0010 0010 0030 0010 0010 0010 0030 0010 0010 0010 0ACD

$ irptransmogrifier render denon-k --name D=4,S=1,F=368 --pronto -p
[org.harctoolbox.cmdline.CommandRender$Renderer render] WARNING: No output requested. Use either --raw, --raw-without-signs, --pronto, --modulate, or --printparameters to get output.
```
This is a reported bug in JCommander https://github.com/cbeust/jcommander/issues/530, since over a year, that the maintainer does not seems to care about.

I will not fix.

**Comment by mkarg** [comment]
> This is a reported bug in JCommander [cbeust/jcommander#530](https://github.com/cbeust/jcommander/issues/530), since over a year, that the maintainer does not seems to care about.
> 
> I will not fix.

Being one of the maintainers of JCommander I need to correct your view on this. At JCommander we do not see it as our task to fix all issues *on our own*, as we all are volunteers. Instead, the maintainers see their job solely as *managers*. Everybody is encouraged to send in PRs with proposed bug fixes. We simply *review* them.

If the bug still exists in JCommander 1.83 then feel free to provide a PR containing a unit test prooving your claim and a proposal for a fix. We guarantee we will review it eventually.
