### ISSUE TITLE
Many protocols have no repeat marker in IrpProtocols.xml

### ISSUE THREAD

**Issue by seanyoung** [bengtmartensson/IrpTransmogrifier#230]
For example, Sony8 is defined as `{40k,600}<1,-1|2,-1>(4,-1,F:8,^45m)[F:0..255]`, which means there is no repeat, there is only a key down event. This is true for many protocols, e.g. `48-NEC` as well.

I am not sure this is correct. Surely you can press and hold buttons on these remotes. 

Would the `*` form make more sense here?

```bash
$ ./irptransmogrifier.sh --irp '{40k,600}<1,-1|2,-1>(4,-1,F:8,^45m)[F:0..255]' render -p -n F=255
0000 0068 0009 0000 0060 0018 0030 0018 0030 0018 0030 0018 0030 0018 0030 0018 0030 0018 0030 0018 0030 0468
$ ./irptransmogrifier.sh --irp '{40k,600}<1,-1|2,-1>(4,-1,F:8,^45m)*[F:0..255]' render -p -n F=255
0000 0068 0000 0009 0060 0018 0030 0018 0030 0018 0030 0018 0030 0018 0030 0018 0030 0018 0030 0018 0030 0468
```

I'm happy to create a PR which fixes these protocols.

**Comment by bengtmartensson** [comment]
Hi Sean,

thank you for the suggestion. The 48-NEC (as well as all protocols ending with "NEC") is (are) correct and meaningful; it (they) represent(s) an incomplete learn. Note that decode-only is set to true. It is (they are) not first-class protocols. (This is explained in the documentation.) Sony8: I do not recall right now where it is used, however, I suspect that it can be argued that it is not a really professional protocol either.

But I take the view that I have just "inherited" the protocols from the [JP1 community/forum](http://www.hifi-remote.com/forums/index.php), in particular [DecodeIR](http://www.hifi-remote.com/wiki/index.php/DecodeIR) (Quite antique, but is linked to incredibly often, in this year 2023.) So I would suggest that you create one or more discussions there, before we change the definitions.

I will be unavailable for the next few days, sorry.

**Comment by seanyoung** [comment]
As always, thank you for your insight.

**Comment by seanyoung** [comment]
I've posted: http://www.hifi-remote.com/forums/viewtopic.php?t=103217
