### ISSUE TITLE
Per default, disallow BitFields widths > 63.

### ISSUE THREAD

**Issue by bengtmartensson** [bengtmartensson/IrpTransmogrifier#234]
Replaces #232. Thank you @seanyoung!

The implementation of Bitfields is based upon the Java data type long/Long, thus designed for a maximal width of 63, although it is planned (#38) to lift this limit. (It is quite possible that this will never be implemented...) It is desirable, at least in the context of analyzing protocols with large payloads (e.g. A/C) to use longer widths, and this even (at least partially) works:

```
$ irptransmogrifier  render --random -p fujitsu_aircon | irptransmogrifier analyze --input - --maxparameterwidth 1000
{38.4k,417,msb}<1,-1|1,-3>(8,-3,A:128,1,-104m){A=0x28c60008087f900c0ed121770554049e}
```
Allowing > 63 bits has never been systematically tested, and not even I know exactly what works and what doesn't. So allowing it per defaults is unprofessional. Still, the above use is valuable.

Plan is to disallow > 63 bits per default; however have an option to accept longer. This should be invoked if  using the analyzer and maxparameterwidth > 63. Currently, except for this, the option need not be accessible from the command line.

**Comment by bengtmartensson** [comment]
Just checked in  a fix to branch  refactor-bitfields. Would be happy for tests and/or feedback.

**Comment by seanyoung** [comment]
Looks great to me, I actually prefer it to my solution. Very nice.

I'm running the fuzzer now it works very well. It's not finding wrong with long bitfield lengths. Perfect!
