### ISSUE TITLE
bit lengths > 63 still supported

### ISSUE THREAD

**Issue by seanyoung** [bengtmartensson/IrpTransmogrifier#235]
```bash
./irptransmogrifier.sh --irp '{100}<1,-1|1,-3>(F:S)' render -r -n F=0,S=990000
```

This brings up a lot of false positives when comparing IrpTransmogrifier to the rust irp implementation.

**Comment by bengtmartensson** [comment]
Thank you for the report. I hope that fix shows to be OK.
