### ISSUE TITLE
line comments don't always work

### ISSUE THREAD

**Issue by seanyoung** [bengtmartensson/IrpTransmogrifier#244]
Should be supported: http://www.harctoolbox.org/IrpTransmogrifier.html#Comments

However:
```bash
$ ./irptransmogrifier --irp '{10}<>(1,-10m)//' render -r 
null
IRP parse error
```
Line comments seem to work else where, just not at the end.

**Comment by bengtmartensson** [comment]
> "//", extending to the end of line)

... which _includes_ the line ending. Your example has no line ending, so I do not consider it valid. Also,

    new Protocol("{36k,msb,889}<1,-1|-1,1>((1,~F:1:6,T:1,D:5,F:6,^114m)*,T=1-T)[D:0..31,F:0..127,T@:0..1=0]// blahblah\n");

parses.
