### ISSUE TITLE
Accept .irp file as input to 'render'

### ISSUE THREAD

**Issue by molexx** [bengtmartensson/IrpTransmogrifier#71]
I'm trying to convert a lirc config to pronto hex using the commandline.

The 'lirc' subcommand has generated an .irp file, and I see that 'render' accepts an irp string - I'm not sure how that string relates to the .irp file generated.

**Comment by bengtmartensson** [comment]
First, [IrScrutinizer](https://github.com/bengtmartensson/harctoolboxbundle) supports this use case directly, and is much user friendlier, GUI etc. 

The `lirc` subcommand is not really intended to do this; it is rather a "research command". For example, it does not clean up the generated form. 

The `render` subcommand has an option `--irp` where you can put the just generated IRP (as text, not file name). Of course, you can do some shell backtick stuff...

If you think your usecase should be directly supported I will be happy to listen to your arguments.

**Comment by molexx** [comment]
Thanks for the reply. I've used IrScrutinizer's GUI with success but I want a commandline tool I can call from a script. It seems that IrpTransmogrifier is very close to what I'm looking for, if it is then I'd appreciate the enhancement please.

I've tried inserting the generated IRP to the --irp option but not had any success. I suspect I'm misusing it... here's what I've tried - using an Apple TV remote config from the lirc site:

```
./irptransmogrifier.sh lirc -c A1294.lircd.conf
Apple_A1294:    {38.0k,1,msb}<608u,-518u|608u,-1618u>(9140u,-4390u,pre_data:16,F:8,post_data:8,610u,^107219,(9141u,-2157u,610u,^107219)*){pre_data=0x77e1,post_data=0x79}[F:0x0..0xff]
KEY_UP: 50
KEY_DOWN:       30
KEY_LEFT:       90
KEY_RIGHT:      60
KEY_PLAY:       fa
KEY_MENU:       c0
KEY_OK: 3a
```

then, to try to convert the irp to pronto:
```
./irptransmogrifier.sh render -p -i `cat a1294.irp`
```
but there's no output.  

In case there's something wrong with the backticks I try manually passing the header and just one of the keys:
```
./irptransmogrifier.sh render -p -i '{38.0k,1,msb}<608u,-518u|608u,-1618u>(9140u,-4390u,pre_data:16,F:8,post_data:8,610u,^107219,(9141u,-2157u,610u,^107219)*){pre_data=0x77e1,post_data=0x79}[F:0x0..0xff] c0'
```
this also results in no output.

**Comment by bengtmartensson** [comment]
> I've used IrScrutinizer's GUI with success but I want a commandline tool I can call from a script.

I still consider this to be an IrScrutinizer issue. I am well aware of the shortcoming of the command line, and [plan to fix it](https://github.com/bengtmartensson/harctoolboxbundle/issues/26). BTW, note that you can throw a directory (not just a file/URL) at IrScrutizer, and  it will recursive scan the directories, parsing everything it can -- this might remove the need of scripting?

> this also results in no output.

But there are definitely an error message, and I have put a lot of efforts to make the error message understandable (for the qualified user).

Your calling syntax is wrong. Try this command line:

    irptransmogrifier render  -p -i `irptransmogrifier  lirc https://sourceforge.net/p/lirc-remotes/code/ci/master/tree/remotes/yamaha/RX-V995.lircd.conf?format=raw | sed -e s/^[^:]\*://` -n F=0xc738

Awkward? Yes, but recall that it is not a natively supported use case.

**Comment by molexx** [comment]
Thanks, that works! The awkward isn't a problem now I know how to use it, I can script that up.

I was missing the sed and the -n parameter. Not showing errors appears to be a git-bash on Windows problem (?).

Background:
I'm writing a script to ease the pain of learning/converting entire remotes to the codes for Broadlink controllers and then HomeAssistant's .yaml format. Many people set up HA on a headless raspberry pi with no GUI and of course prefer a script they can just run without any clicking about on a complex interface. So I need commandline tools to convert between the database formats. Pronto is the best target as there's a script `pronto2broadlink.py` which will add the Broadlink headers.

As an aside I'd also like to replace my ugly runtime dependency on scraping irdb.tk with a commandline tool to convert from 'protocol, device, subdevice, function' to pronto, I guess IrScrutinizer will be able to do that for me too when it's commandline functionality is implemented.

Thanks!

**Comment by bengtmartensson** [comment]
> I'm writing a script to ease the pain of learning/converting entire remotes to the codes for Broadlink controllers and then HomeAssistant's .yaml format. 

Converting is a thing that needs to be done only once. Consider contributing an backend, "exportformat" for those targets, cf. [this issue](https://github.com/bengtmartensson/harctoolboxbundle/issues/208) and [this](https://github.com/bengtmartensson/harctoolboxbundle/issues/207) :-).

**Comment by molexx** [comment]
That would be good!

Thanks for your help, closing this issue.

**Comment by bengtmartensson** [comment]
Update (if someone reads this still): the -i (--irp) option is now a "common option", i.e. should be given before "render". So the "awkward" command should be

    irptransmogrifier  -i `irptransmogrifier  lirc https://sourceforge.net/p/lirc-remotes/code/ci/master/tree/remotes/yamaha/RX-V995.lircd.conf?format=raw | sed -e s/^[^:]\*://` render  -p -n F=0xc738
