### ISSUE TITLE
irptransmogrifier.bat cmd error

### ISSUE THREAD

**Issue by Pavlex4** [bengtmartensson/IrpTransmogrifier#95]
I downloaded bengtmartensson/IrpTransmogrifier source from github and I opened command prompt in IrpTransmogrifier-master\src\main\config and after I executed irptransmogrifier.bat I got error:
Error: Unable to access jarfile C:\Users\pavle\Desktop\Files\IR\IrpTransmogrifier-master\IrpTransmogrifier-master\src\main\config\\IrpTransmogrifier-${project.version}-jar-with-dependencies.jar 
How to fix this?

**Comment by Pavlex4** [comment]
I tried to build project with Intellij Idea program and I got errors that say: java: package IrpParser does not exist

**Comment by Pavlex4** [comment]
Which program I should use to build project?

**Comment by bengtmartensson** [comment]
Since you are using Intellij, it  [supports Maven projects](https://www.jetbrains.com/help/idea/maven-support.html#maven_import_project_start) so you should probably try to get that working. 

Otherwise, [Maven download](https://maven.apache.org/download.cgi).

**Comment by Pavlex4** [comment]
I opened maven projects window like here https://www.youtube.com/watch?v=AiFZfubsW-s and I compiled project successfully. After that I opened command prompt in target folder and after typing irptransmogrifier.bat I got same error again

**Comment by bengtmartensson** [comment]
Upload target/irptransmogrifier.bat.

**Comment by Pavlex4** [comment]
Here: https://www.sendspace.com/file/h9e9ah

**Comment by bengtmartensson** [comment]
That file is OK. There is no way it can generate "the same error". Something else must be in error.

Of course, you can edit APPLICATIONHOME to the real name of the directory.

**Comment by Pavlex4** [comment]
Can you please send me compiled project?

**Comment by bengtmartensson** [comment]
https://github.com/bengtmartensson/IrpTransmogrifier/releases/download/ci-build/IrpTransmogrifier-0.2.1dev-bin.zip

**Comment by Pavlex4** [comment]
Thank you very much!
